services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - classificacao


  webserver:
    image: 'nginx:alpine'
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    ports:
      - '8080:80'
    networks:
      - classificacao

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: desafio_backend
    volumes:
      - ./docker/dbpostgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - classificacao
         
networks:
    classificacao:
        driver: bridge