services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - teste_desafio


  webserver:
    image: 'nginx:alpine'
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    ports:
      - '8080:80'
    networks:
      - teste_desafio

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: teste_desafio_backend
    volumes:
      - ./docker/dbpostgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - teste_desafio
         
networks:
    teste_desafio:
        driver: bridge